"""tags

Revision ID: 1c03fe48a5d7
Revises: 3f21f3285683
Create Date: 2015-01-19 18:06:51.741021

"""

# revision identifiers, used by Alembic.
revision = '1c03fe48a5d7'
down_revision = '3f21f3285683'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
