"""initial

Revision ID: 1f589b4d7c97
Revises: None
Create Date: 2015-01-19 15:42:17.370020

"""

# revision identifiers, used by Alembic.
revision = '1f589b4d7c97'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
