"""tags2

Revision ID: 347d71dfa207
Revises: 1c03fe48a5d7
Create Date: 2015-01-21 10:36:14.533230

"""

# revision identifiers, used by Alembic.
revision = '347d71dfa207'
down_revision = '1c03fe48a5d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
